# Generated by Django 4.2.7 on 2025-09-18 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum file upload size in MB (1-1024 MB)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1024),
                        ],
                    ),
                ),
                (
                    "max_files_per_message",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum number of files per message (1-20)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "allowed_file_extensions",
                    models.TextField(
                        default="txt,pdf,doc,docx,xls,xlsx,jpg,jpeg,png,gif,webp",
                        help_text="Comma-separated list of allowed file extensions (without dots)",
                    ),
                ),
                (
                    "session_timeout_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="User session timeout in hours",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                (
                    "messages_per_page",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Number of messages to load per page (pagination)",
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "api_requests_per_minute",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Maximum API requests per minute per user",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global Settings",
                "verbose_name_plural": "Global Settings",
            },
        ),
    ]
