# Generated by Django 4.2.7 on 2025-09-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsAndConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="شرایط و قوانین استفاده",
                        max_length=200,
                        verbose_name="عنوان",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        default="شرایط و قوانین استفاده از سرویس در اینجا قرار خواهد گرفت.",
                        help_text="محتوای شرایط و قوانین استفاده از سرویس را وارد کنید",
                        verbose_name="محتوای شرایط و قوانین",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "شرایط و قوانین",
                "verbose_name_plural": "شرایط و قوانین",
                "db_table": "terms_and_conditions",
            },
        ),
    ]
