# Generated by Django 4.2.7 on 2025-10-05 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_termsandconditions"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان بنر")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="تصویر بنر تبلیغاتی",
                        null=True,
                        upload_to="banners/",
                        verbose_name="تصویر بنر",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        help_text="لینک مقصد بنر", max_length=500, verbose_name="لینک"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "بنر تبلیغاتی",
                "verbose_name_plural": "بنرهای تبلیغاتی",
                "db_table": "advertising_banners",
                "ordering": ["-created_at"],
            },
        ),
    ]
