# Generated by Django 4.2.7 on 2025-09-14 11:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0012_remove_subscriptiontype_daily_pdf_processing_limit_and_more",
        ),
        ("ai_models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebSearchSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Web Search Settings", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enabled_subscription_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Subscription types that can use web search functionality",
                        to="subscriptions.subscriptiontype",
                    ),
                ),
                (
                    "web_search_model",
                    models.ForeignKey(
                        help_text="AI model to use for web search functionality",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_search_settings",
                        to="ai_models.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web Search Settings",
                "verbose_name_plural": "Web Search Settings",
                "db_table": "web_search_settings",
            },
        ),
    ]
