# Generated by Django 4.2.7 on 2025-09-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0002_websearchsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="token_cost_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Cost multiplier for this model. Example: 2.0 means double the cost.",
                max_digits=5,
            ),
        ),
    ]
