# Generated by Django 4.2.7 on 2025-09-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0003_aimodel_token_cost_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image for this AI model",
                null=True,
                upload_to="model_images/",
            ),
        ),
    ]
