# Generated by Django 4.2.7 on 2025-10-06 06:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0004_aimodel_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("content", models.TextField()),
                ("excerpt", models.TextField(blank=True, max_length=300)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for this article",
                        null=True,
                        upload_to="article_images/",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article",
                        to="ai_models.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Article",
                "verbose_name_plural": "Model Articles",
                "db_table": "model_articles",
            },
        ),
    ]
