# Generated by Django 4.2.7 on 2025-10-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0005_modelarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelarticle",
            name="show_login_register",
            field=models.BooleanField(
                default=False, help_text="Show this article on login/register pages"
            ),
        ),
    ]
