# Generated by Django 4.2.7 on 2025-09-11 14:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0001_initial"),
        ("subscriptions", "0002_usagelimit_max_free_model_messages_and_more"),
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="ai_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_models.aimodel",
            ),
        ),
        migrations.CreateModel(
            name="Chatbot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, help_text="System prompt for the AI model"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_models.aimodel",
                    ),
                ),
                (
                    "subscription_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="chatbots",
                        to="subscriptions.subscriptiontype",
                    ),
                ),
            ],
            options={
                "db_table": "chatbots",
            },
        ),
        migrations.AddField(
            model_name="chatsession",
            name="chatbot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot.chatbot",
            ),
        ),
    ]
