# Generated by Django 4.2.7 on 2025-09-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0001_initial"),
        ("chatbot", "0002_alter_chatsession_ai_model_chatbot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="ai_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_models.aimodel",
            ),
        ),
    ]
