# Generated by Django 4.2.7 on 2025-09-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_alter_chatbot_ai_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatbot",
            name="ai_model",
        ),
    ]
