# Generated by Django 4.2.7 on 2025-09-12 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_delete_sessionusage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatbot", "0004_remove_chatbot_ai_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSessionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tokens_count",
                    models.IntegerField(
                        default=0, help_text="Total tokens used in this session"
                    ),
                ),
                (
                    "free_model_tokens_count",
                    models.IntegerField(
                        default=0,
                        help_text="Tokens used with free models in this session",
                    ),
                ),
                (
                    "is_free_model",
                    models.BooleanField(
                        default=False, help_text="Whether this session used free models"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="chatbot.chatsession",
                    ),
                ),
                (
                    "subscription_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.subscriptiontype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_session_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_session_usages",
                "ordering": ["-created_at"],
            },
        ),
    ]
