# Generated by Django 4.2.7 on 2025-09-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_chatsessionusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="chatbot_type",
            field=models.CharField(
                choices=[("text", "Text Generator"), ("image", "Image Generator")],
                default="text",
                help_text="Type of chatbot (text or image generation)",
                max_length=10,
            ),
        ),
    ]
