# Generated by Django 4.2.7 on 2025-09-13 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatbot", "0006_chatbot_chatbot_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="generated_images/")),
                (
                    "original_prompt",
                    models.TextField(
                        blank=True,
                        help_text="The original prompt used to generate this image",
                    ),
                ),
                (
                    "modification_prompt",
                    models.TextField(
                        blank=True, help_text="The prompt used to modify this image"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_images",
                        to="chatbot.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "generated_images",
                "ordering": ["-created_at"],
            },
        ),
    ]
