# Generated by Django 4.2.7 on 2025-09-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0009_websearch_pdfdocument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="websearch",
            name="session",
        ),
        migrations.RemoveField(
            model_name="websearch",
            name="user",
        ),
        migrations.DeleteModel(
            name="PDFDocument",
        ),
        migrations.DeleteModel(
            name="WebSearch",
        ),
    ]
