# Generated by Django 4.2.7 on 2025-09-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0010_remove_websearch_session_remove_websearch_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="uploaded_images",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="chatbot.useruploadedimage"
            ),
        ),
    ]
