# Generated by Django 4.2.7 on 2025-09-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0011_chatmessage_uploaded_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useruploadedimage",
            name="session",
        ),
        migrations.RemoveField(
            model_name="useruploadedimage",
            name="user",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="uploaded_images",
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="chatbot_type",
            field=models.CharField(
                choices=[("text", "Text Generator")],
                default="text",
                help_text="Type of chatbot (text generation)",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="GeneratedImage",
        ),
        migrations.DeleteModel(
            name="UserUploadedImage",
        ),
    ]
