# Generated by Django 4.2.7 on 2025-09-14 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0013_financialtransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatbot", "0012_remove_useruploadedimage_session_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Unique filename for storage", max_length=255
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename from user", max_length=255
                    ),
                ),
                (
                    "mimetype",
                    models.CharField(help_text="MIME type of the file", max_length=100),
                ),
                ("size", models.PositiveIntegerField(help_text="File size in bytes")),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="chatbot.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uploaded_files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="FileUploadSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_file_size",
                    models.PositiveIntegerField(
                        help_text="Maximum file size in bytes (0 for unlimited)"
                    ),
                ),
                (
                    "allowed_extensions",
                    models.TextField(
                        help_text="Comma-separated list of allowed file extensions"
                    ),
                ),
                (
                    "max_files_per_chat",
                    models.PositiveIntegerField(
                        help_text="Maximum files per chat session (0 for unlimited)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether these settings are active"
                    ),
                ),
                (
                    "subscription_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_upload_settings",
                        to="subscriptions.subscriptiontype",
                    ),
                ),
            ],
            options={
                "db_table": "file_upload_settings",
            },
        ),
    ]
