# Generated by Django 4.2.7 on 2025-09-15 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0002_websearchsettings"),
        ("chatbot", "0013_uploadedfile_fileuploadsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileProcessingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="File Processing Settings", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_model",
                    models.ForeignKey(
                        help_text="AI model to use for file processing and analysis",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_processing_settings",
                        to="ai_models.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Processing Settings",
                "verbose_name_plural": "File Processing Settings",
                "db_table": "file_processing_settings",
            },
        ),
    ]
