# Generated by Django 4.2.7 on 2025-09-15 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_models", "0002_websearchsettings"),
        ("chatbot", "0014_fileprocessingsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisionProcessingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Vision Processing Settings", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_model",
                    models.ForeignKey(
                        help_text="AI model to use for vision/image processing and analysis",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vision_processing_settings",
                        to="ai_models.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vision Processing Settings",
                "verbose_name_plural": "Vision Processing Settings",
                "db_table": "vision_processing_settings",
            },
        ),
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file", models.ImageField(upload_to="image_uploads/")),
                ("analysis_result", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_images",
                        to="chatbot.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uploaded_images",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
