# Generated by Django 4.2.7 on 2025-09-15 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0013_financialtransaction"),
        ("chatbot", "0015_visionprocessingsettings_uploadedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileuploadsettings",
            name="daily_file_limit",
            field=models.PositiveIntegerField(
                default=0, help_text="Maximum files per day (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="fileuploadsettings",
            name="monthly_file_limit",
            field=models.PositiveIntegerField(
                default=0, help_text="Maximum files per month (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="fileuploadsettings",
            name="weekly_file_limit",
            field=models.PositiveIntegerField(
                default=0, help_text="Maximum files per week (0 for unlimited)"
            ),
        ),
        migrations.CreateModel(
            name="FileUploadUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_files_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Files uploaded today"
                    ),
                ),
                (
                    "weekly_files_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Files uploaded this week"
                    ),
                ),
                (
                    "monthly_files_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Files uploaded this month"
                    ),
                ),
                (
                    "session_files_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Files uploaded in current session"
                    ),
                ),
                (
                    "daily_period_start",
                    models.DateTimeField(help_text="Start of daily period"),
                ),
                (
                    "weekly_period_start",
                    models.DateTimeField(help_text="Start of weekly period"),
                ),
                (
                    "monthly_period_start",
                    models.DateTimeField(help_text="Start of monthly period"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.subscriptiontype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_upload_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "file_upload_usage",
                "unique_together": {("user", "subscription_type")},
            },
        ),
    ]
