# Generated by Django 4.2.7 on 2025-09-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0016_fileuploadsettings_daily_file_limit_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileProcessingSettings",
        ),
    ]
