# Generated by Django 4.2.7 on 2025-09-15 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('accounts', '0001_initial'),
        ('chatbot', '0017_delete_fileprocessingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='chatbot_type',
            field=models.CharField(choices=[('text', 'Text Generator'), ('image_editing', 'Image Editing')], default='text', help_text='Type of chatbot (text generation)', max_length=20),
        ),
        migrations.CreateModel(
            name='ImageGenerationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_images_count', models.PositiveIntegerField(default=0, help_text='Images generated today')),
                ('weekly_images_count', models.PositiveIntegerField(default=0, help_text='Images generated this week')),
                ('monthly_images_count', models.PositiveIntegerField(default=0, help_text='Images generated this month')),
                ('daily_period_start', models.DateTimeField(help_text='Start of daily period')),
                ('weekly_period_start', models.DateTimeField(help_text='Start of weekly period')),
                ('monthly_period_start', models.DateTimeField(help_text='Start of monthly period')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_generation_usage', to='accounts.user')),
            ],
            options={
                'db_table': 'image_generation_usage',
                'unique_together': {('user', 'subscription_type')},
            },
        ),
    ]