# Generated by Django 4.2.7 on 2025-09-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_add_image_editing_chatbot_and_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='chatbot_type',
            field=models.CharField(choices=[('text', 'Text Generator'), ('image_editing', 'Image Editing')], default='text', help_text='Type of chatbot (text generation)', max_length=20),
        ),
    ]