# Generated by Django 4.2.7 on 2025-09-16 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0002_websearchsettings"),
        ("chatbot", "0019_alter_chatbot_chatbot_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultChatSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Default Chat Settings", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_ai_model",
                    models.ForeignKey(
                        help_text="مدل پیش\u200cفرض برای جلسات جدید",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_chat_settings",
                        to="ai_models.aimodel",
                    ),
                ),
                (
                    "default_chatbot",
                    models.ForeignKey(
                        help_text="چت\u200cبات پیش\u200cفرض برای جلسات جدید",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_chat_settings",
                        to="chatbot.chatbot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Default Chat Settings",
                "verbose_name_plural": "Default Chat Settings",
                "db_table": "default_chat_settings",
            },
        ),
    ]
