# Generated by Django 4.2.7 on 2025-09-16 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0020_defaultchatsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SidebarMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the menu item", max_length=100
                    ),
                ),
                (
                    "url_name",
                    models.CharField(help_text="Django URL name", max_length=100),
                ),
                (
                    "icon_class",
                    models.CharField(
                        default="fas fa-link",
                        help_text="Font Awesome icon class",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of display (lower numbers first)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "required_permission",
                    models.CharField(
                        blank=True,
                        help_text="Required permission to view this item (optional)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sidebar_menu_items",
                "ordering": ["order", "name"],
            },
        ),
    ]