# Generated by Django 4.2.7 on 2025-09-16 16:16

from django.db import migrations


def create_default_menu_items(apps, schema_editor):
    SidebarMenuItem = apps.get_model('chatbot', 'SidebarMenuItem')
    
    # Create default menu items
    default_items = [
        {
            'name': 'خانه',
            'url_name': 'home',
            'icon_class': 'fas fa-home',
            'order': 1,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'چت',
            'url_name': 'chat:chat',
            'icon_class': 'fas fa-comments',
            'order': 2,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'داشبورد',
            'url_name': 'dashboard',
            'icon_class': 'fas fa-tachometer-alt',
            'order': 3,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'تراکنش‌های مالی',
            'url_name': 'financial_transactions',
            'icon_class': 'fas fa-credit-card',
            'order': 4,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'خرید اشتراک',
            'url_name': 'purchase_subscription',
            'icon_class': 'fas fa-shopping-cart',
            'order': 5,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'خروج',
            'url_name': 'logout',
            'icon_class': 'fas fa-sign-out-alt',
            'order': 6,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'ورود',
            'url_name': 'login',
            'icon_class': 'fas fa-sign-in-alt',
            'order': 7,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'پروفایل',
            'url_name': 'profile',
            'icon_class': 'fas fa-user',
            'order': 8,
            'is_active': True,
            'required_permission': None
        }
    ]
    
    # Create menu items that don't already exist
    for item_data in default_items:
        # Check if item already exists
        existing_item = SidebarMenuItem.objects.filter(url_name=item_data['url_name']).first()
        if not existing_item:
            SidebarMenuItem.objects.create(**item_data)


def reverse_default_menu_items(apps, schema_editor):
    SidebarMenuItem = apps.get_model('chatbot', 'SidebarMenuItem')
    
    # Remove default menu items
    url_names = ['home', 'chat:chat', 'dashboard', 'financial_transactions', 'purchase_subscription', 'logout', 'login', 'profile']
    SidebarMenuItem.objects.filter(url_name__in=url_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0022_sidebarmenuitem"),
    ]

    operations = [
        migrations.RunPython(create_default_menu_items, reverse_default_menu_items),
    ]