# Generated by Django 4.2.7 on 2025-09-16 16:28

from django.db import migrations


def update_menu_items(apps, schema_editor):
    SidebarMenuItem = apps.get_model('chatbot', 'SidebarMenuItem')
    
    # Update existing menu items to use namespaced URLs
    chat_item = SidebarMenuItem.objects.filter(url_name='chat').first()
    if chat_item:
        chat_item.url_name = 'chat:chat'
        chat_item.save()
    
    # Remove old login/logout items if they exist (they'll be recreated with correct order)
    SidebarMenuItem.objects.filter(url_name__in=['login', 'logout']).delete()
    
    # Create updated menu items
    updated_items = [
        {
            'name': 'خانه',
            'url_name': 'home',
            'icon_class': 'fas fa-home',
            'order': 1,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'چت',
            'url_name': 'chat:chat',
            'icon_class': 'fas fa-comments',
            'order': 2,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'داشبورد',
            'url_name': 'dashboard',
            'icon_class': 'fas fa-tachometer-alt',
            'order': 3,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'تراکنش‌های مالی',
            'url_name': 'financial_transactions',
            'icon_class': 'fas fa-credit-card',
            'order': 4,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'خرید اشتراک',
            'url_name': 'purchase_subscription',
            'icon_class': 'fas fa-shopping-cart',
            'order': 5,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'خروج',
            'url_name': 'logout',
            'icon_class': 'fas fa-sign-out-alt',
            'order': 6,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'ورود',
            'url_name': 'login',
            'icon_class': 'fas fa-sign-in-alt',
            'order': 7,
            'is_active': True,
            'required_permission': None
        },
        {
            'name': 'پروفایل',
            'url_name': 'profile',
            'icon_class': 'fas fa-user',
            'order': 8,
            'is_active': True,
            'required_permission': None
        }
    ]
    
    # Create or update menu items
    for item_data in updated_items:
        # Check if item already exists
        existing_item = SidebarMenuItem.objects.filter(url_name=item_data['url_name']).first()
        if existing_item:
            # Update existing item
            for key, value in item_data.items():
                setattr(existing_item, key, value)
            existing_item.save()
        else:
            # Create new item
            SidebarMenuItem.objects.create(**item_data)


def reverse_menu_items_update(apps, schema_editor):
    SidebarMenuItem = apps.get_model('chatbot', 'SidebarMenuItem')
    
    # Revert chat item URL
    chat_item = SidebarMenuItem.objects.filter(url_name='chat:chat').first()
    if chat_item:
        chat_item.url_name = 'chat'
        chat_item.save()
    
    # Remove added items
    url_names = ['home', 'dashboard', 'financial_transactions', 'profile']
    SidebarMenuItem.objects.filter(url_name__in=url_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0023_auto_20250916_1946"),
    ]

    operations = [
        migrations.RunPython(update_menu_items, reverse_menu_items_update),
    ]