# Generated by Django 4.2.7 on 2025-09-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0025_sidebarmenuitem_show_only_for_authenticated"),
    ]

    operations = [
        migrations.AddField(
            model_name="sidebarmenuitem",
            name="show_only_for_non_authenticated",
            field=models.BooleanField(
                default=False,
                help_text="If True, this menu item will only be shown to non-authenticated users",
            ),
        ),
    ]
