# Generated by Django 4.2.7 on 2025-09-17 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0026_sidebarmenuitem_show_only_for_non_authenticated"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="message_id",
            field=models.UUIDField(editable=False, unique=True, null=True),  # No default value initially
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="needs_regeneration",
            field=models.BooleanField(default=False),
        ),
    ]