# Generated by Django 4.2.7 on 2025-09-17 06:52

from django.db import migrations
import uuid

def populate_message_ids(apps, schema_editor):
    ChatMessage = apps.get_model('chatbot', 'ChatMessage')
    for message in ChatMessage.objects.all():
        message.message_id = uuid.uuid4()
        message.save()

def reverse_populate_message_ids(apps, schema_editor):
    # Nothing to do here
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0027_add_message_editing_fields"),
    ]

    operations = [
        migrations.RunPython(populate_message_ids, reverse_populate_message_ids),
    ]