# Generated by Django 4.2.7 on 2025-09-17 06:54

from django.db import migrations, models
import uuid

def set_message_id_default(apps, schema_editor):
    ChatMessage = apps.get_model('chatbot', 'ChatMessage')
    for message in ChatMessage.objects.filter(message_id__isnull=True):
        message.message_id = uuid.uuid4()
        message.save()

def reverse_set_message_id_default(apps, schema_editor):
    # Nothing to do here
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0028_populate_message_ids"),
    ]

    operations = [
        migrations.RunPython(set_message_id_default, reverse_set_message_id_default),
        migrations.AlterField(
            model_name="chatmessage",
            name="message_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]