# Generated by Django 4.2.7 on 2025-09-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0029_set_message_id_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
    ]
