# Generated by Django 4.2.7 on 2025-09-19 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0030_add_disabled_field_to_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="LimitationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "limitation_type",
                    models.CharField(
                        choices=[
                            ("token_limit", "Token Limit Reached"),
                            ("message_limit", "Message Limit Reached"),
                            ("daily_limit", "Daily Limit Reached"),
                            ("weekly_limit", "Weekly Limit Reached"),
                            ("monthly_limit", "Monthly Limit Reached"),
                            ("file_upload_limit", "File Upload Limit Reached"),
                            (
                                "image_generation_limit",
                                "Image Generation Limit Reached",
                            ),
                            ("subscription_required", "Subscription Required"),
                            ("model_access_denied", "Model Access Denied"),
                            ("general_limit", "General Limit Reached"),
                        ],
                        help_text="Type of limitation this message applies to",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the limitation message", max_length=200
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="The message content to show to users"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Limitation Message",
                "verbose_name_plural": "Limitation Messages",
                "db_table": "limitation_messages",
                "ordering": ["limitation_type"],
            },
        ),
    ]
