# Generated by Django 4.2.7 on 2025-09-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0032_limitationmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="auto_generate_title",
            field=models.BooleanField(
                default=True,
                help_text="Whether to auto-generate title from first message",
            ),
        ),
    ]
