# Generated by Django 4.2.7 on 2025-09-20 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0033_add_auto_generate_title_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of file in the message"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="chatbot.chatmessage",
                    ),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_files",
                        to="chatbot.uploadedfile",
                    ),
                ),
            ],
            options={
                "db_table": "message_files",
                "ordering": ["file_order", "created_at"],
                "unique_together": {("message", "uploaded_file")},
            },
        ),
    ]