# Generated by Django 4.2.7 on 2025-09-29 08:30

from django.db import migrations


def fix_chat_url_names(apps, schema_editor):
    SidebarMenuItem = apps.get_model('chatbot', 'SidebarMenuItem')
    
    # Fix chat item URL from 'chat:chat' to 'chat'
    chat_items = SidebarMenuItem.objects.filter(url_name='chat:chat')
    for item in chat_items:
        item.url_name = 'chat'
        item.save()


def reverse_chat_url_names(apps, schema_editor):
    SidebarMenuItem = apps.get_model('chatbot', 'SidebarMenuItem')
    
    # Revert chat item URL from 'chat' to 'chat:chat'
    chat_items = SidebarMenuItem.objects.filter(url_name='chat')
    for item in chat_items:
        item.url_name = 'chat:chat'
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0034_messagefile'),
    ]

    operations = [
        migrations.RunPython(fix_chat_url_names, reverse_chat_url_names),
    ]