# Generated by Django 4.2.7 on 2025-10-02 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0017_delete_defaultsubscriptionsettings"),
        ("chatbot", "0035_fix_chat_url_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenRouterRequestCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="OpenRouter model ID used for the request",
                        max_length=100,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Human-readable model name", max_length=200
                    ),
                ),
                (
                    "prompt_tokens",
                    models.IntegerField(
                        default=0, help_text="Number of tokens in the prompt"
                    ),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(
                        default=0, help_text="Number of tokens in the completion"
                    ),
                ),
                (
                    "total_tokens",
                    models.IntegerField(default=0, help_text="Total tokens used"),
                ),
                (
                    "token_cost_multiplier",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        help_text="Cost multiplier for the model (e.g., 1.5x)",
                        max_digits=10,
                    ),
                ),
                (
                    "effective_cost_tokens",
                    models.IntegerField(
                        default=0,
                        help_text="Effective tokens after applying multiplier",
                    ),
                ),
                (
                    "cost_per_million_tokens",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Cost per million tokens (if available)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Total cost of the request (if calculable)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat Message"),
                            ("title", "Title Generation"),
                            ("edit", "Message Editing"),
                            ("vision", "Vision Processing"),
                        ],
                        default="chat",
                        help_text="Type of request",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openrouter_costs",
                        to="chatbot.chatsession",
                    ),
                ),
                (
                    "subscription_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.subscriptiontype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openrouter_costs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenRouter Request Cost",
                "verbose_name_plural": "OpenRouter Request Costs",
                "db_table": "openrouter_request_costs",
                "ordering": ["-created_at"],
            },
        ),
    ]
