# Generated by Django 4.2.7 on 2025-10-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0036_openrouterrequestcost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openrouterrequestcost",
            name="total_cost",
        ),
        migrations.AddField(
            model_name="openrouterrequestcost",
            name="total_cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Total cost of the request in USD (if calculable)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
