# Generated by Django 4.2.7 on 2025-10-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0037_remove_openrouterrequestcost_total_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="limitationmessage",
            name="limitation_type",
            field=models.CharField(
                choices=[
                    ("token_limit", "Token Limit Reached"),
                    ("message_limit", "Message Limit Reached"),
                    ("daily_limit", "Daily Limit Reached"),
                    ("weekly_limit", "Weekly Limit Reached"),
                    ("monthly_limit", "Monthly Limit Reached"),
                    ("file_upload_limit", "File Upload Limit Reached"),
                    ("image_generation_limit", "Image Generation Limit Reached"),
                    ("subscription_required", "Subscription Required"),
                    ("model_access_denied", "Model Access Denied"),
                    ("general_limit", "General Limit Reached"),
                    ("openrouter_cost_limit", "OpenRouter Cost Limit Reached"),
                ],
                help_text="Type of limitation this message applies to",
                max_length=50,
                unique=True,
            ),
        ),
    ]
