# Generated by Django 4.2.7 on 2025-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0038_alter_limitationmessage_limitation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image for this chatbot",
                null=True,
                upload_to="chatbot_images/",
            ),
        ),
    ]
