# Generated by Django 4.2.7 on 2025-10-12 04:40

from django.db import migrations, models
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0039_chatbot_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openrouterrequestcost",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="openrouterrequestcost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]