# Generated by Django 4.2.7 on 2025-09-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagelimit",
            name="max_free_model_messages",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usagelimit",
            name="max_free_model_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userusage",
            name="free_model_messages_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userusage",
            name="free_model_tokens_count",
            field=models.IntegerField(default=0),
        ),
    ]
