# Generated by Django 4.2.7 on 2025-09-11 22:36

from django.db import migrations, models

def add_fields_to_subscription_type(apps, schema_editor):
    # We can't add the fields directly because of the unique constraint
    # This migration is just a placeholder
    pass

def reverse_add_fields_to_subscription_type(apps, schema_editor):
    # Nothing to do in reverse
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_discountcode_discountuse"),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='duration_days',
            field=models.IntegerField(default=30, help_text='Subscription duration in days'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='sku',
            field=models.CharField(default='DEFAULT_SKU', help_text='Stock Keeping Unit for the subscription', max_length=50),
        ),
    ]