# Generated by Django 4.2.7 on 2025-09-11 22:38

from django.db import migrations, models
from django.utils import timezone

def populate_unique_skus(apps, schema_editor):
    SubscriptionType = apps.get_model('subscriptions', 'SubscriptionType')
    for subscription in SubscriptionType.objects.all():
        # Generate a unique SKU based on the subscription name and current timestamp
        base_sku = subscription.name.replace(' ', '_').upper()
        subscription.sku = f"{base_sku}_{int(timezone.now().timestamp())}"
        subscription.save()

def reverse_populate_unique_skus(apps, schema_editor):
    # Nothing to do in reverse
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_add_subscription_fields"),
    ]

    operations = [
        migrations.RunPython(populate_unique_skus, reverse_populate_unique_skus),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='sku',
            field=models.CharField(help_text='Stock Keeping Unit for the subscription', max_length=50, unique=True),
        ),
    ]