# Generated by Django 4.2.7 on 2025-09-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_fix_subscription_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontype",
            name="max_tokens",
            field=models.IntegerField(
                default=0,
                help_text="Maximum tokens allowed for this subscription (0 for unlimited)",
            ),
        ),
    ]
