# Generated by Django 4.2.7 on 2025-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_subscriptiontype_max_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontype",
            name="daily_max_messages",
            field=models.IntegerField(
                default=0, help_text="Maximum messages per day (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="daily_max_tokens",
            field=models.IntegerField(
                default=0, help_text="Maximum tokens per day (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="hourly_max_messages",
            field=models.IntegerField(
                default=0, help_text="Maximum messages per hour (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="hourly_max_tokens",
            field=models.IntegerField(
                default=0, help_text="Maximum tokens per hour (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="monthly_free_model_messages",
            field=models.IntegerField(
                default=0,
                help_text="Maximum free model messages per month (0 for unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="monthly_free_model_tokens",
            field=models.IntegerField(
                default=0,
                help_text="Maximum free model tokens per month (0 for unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="monthly_max_messages",
            field=models.IntegerField(
                default=0, help_text="Maximum messages per month (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="monthly_max_tokens",
            field=models.IntegerField(
                default=0, help_text="Maximum tokens per month (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="three_hours_max_messages",
            field=models.IntegerField(
                default=0, help_text="Maximum messages per 3 hours (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="three_hours_max_tokens",
            field=models.IntegerField(
                default=0, help_text="Maximum tokens per 3 hours (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="twelve_hours_max_messages",
            field=models.IntegerField(
                default=0, help_text="Maximum messages per 12 hours (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="twelve_hours_max_tokens",
            field=models.IntegerField(
                default=0, help_text="Maximum tokens per 12 hours (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="weekly_max_messages",
            field=models.IntegerField(
                default=0, help_text="Maximum messages per week (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="weekly_max_tokens",
            field=models.IntegerField(
                default=0, help_text="Maximum tokens per week (0 for unlimited)"
            ),
        ),
        migrations.DeleteModel(
            name="UsageLimit",
        ),
    ]
