# Generated by Django 4.2.7 on 2025-09-12 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_remove_chatbot_ai_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0007_subscriptiontype_daily_max_messages_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_created_at", models.DateTimeField()),
                ("is_free_model", models.BooleanField(default=False)),
                ("messages_count", models.IntegerField(default=0)),
                ("tokens_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chatbot.chatsession",
                    ),
                ),
                (
                    "subscription_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.subscriptiontype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "session_usage",
                "ordering": ["-created_at"],
            },
        ),
    ]
