# Generated by Django 4.2.7 on 2025-09-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_add_session_usage_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SessionUsage",
        ),
    ]
