# Generated by Django 4.2.7 on 2025-09-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_delete_sessionusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontype",
            name="daily_image_generation_limit",
            field=models.IntegerField(
                default=10,
                help_text="Maximum images that can be generated per day (0 for unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="monthly_image_generation_limit",
            field=models.IntegerField(
                default=200,
                help_text="Maximum images that can be generated per month (0 for unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="weekly_image_generation_limit",
            field=models.IntegerField(
                default=50,
                help_text="Maximum images that can be generated per week (0 for unlimited)",
            ),
        ),
    ]
