# Generated by Django 4.2.7 on 2025-09-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0010_subscriptiontype_daily_image_generation_limit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontype",
            name="daily_pdf_processing_limit",
            field=models.IntegerField(
                default=5,
                help_text="Maximum PDFs that can be processed per day (0 for unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="daily_web_search_limit",
            field=models.IntegerField(
                default=10, help_text="Maximum web searches per day (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="max_pdf_file_size",
            field=models.IntegerField(
                default=10, help_text="Maximum PDF file size in MB (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="monthly_pdf_processing_limit",
            field=models.IntegerField(
                default=50,
                help_text="Maximum PDFs that can be processed per month (0 for unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="monthly_web_search_limit",
            field=models.IntegerField(
                default=200,
                help_text="Maximum web searches per month (0 for unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="weekly_pdf_processing_limit",
            field=models.IntegerField(
                default=20,
                help_text="Maximum PDFs that can be processed per week (0 for unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="weekly_web_search_limit",
            field=models.IntegerField(
                default=50, help_text="Maximum web searches per week (0 for unlimited)"
            ),
        ),
    ]
