# Generated by Django 4.2.7 on 2025-09-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_subscriptiontype_daily_pdf_processing_limit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptiontype",
            name="daily_pdf_processing_limit",
        ),
        migrations.RemoveField(
            model_name="subscriptiontype",
            name="daily_web_search_limit",
        ),
        migrations.RemoveField(
            model_name="subscriptiontype",
            name="max_pdf_file_size",
        ),
        migrations.RemoveField(
            model_name="subscriptiontype",
            name="monthly_pdf_processing_limit",
        ),
        migrations.RemoveField(
            model_name="subscriptiontype",
            name="monthly_web_search_limit",
        ),
        migrations.RemoveField(
            model_name="subscriptiontype",
            name="weekly_pdf_processing_limit",
        ),
        migrations.RemoveField(
            model_name="subscriptiontype",
            name="weekly_web_search_limit",
        ),
    ]
