# Generated by Django 4.2.7 on 2025-09-14 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "subscriptions",
            "0012_remove_subscriptiontype_daily_pdf_processing_limit_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("subscription_purchase", "Subscription Purchase"),
                            ("subscription_upgrade", "Subscription Upgrade"),
                            ("subscription_renewal", "Subscription Renewal"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in Tomans", max_digits=10
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original amount before discounts in Tomans",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount amount in Tomans",
                        max_digits=10,
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        help_text="Payment authority from gateway",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference ID from payment gateway",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.discountcode",
                    ),
                ),
                (
                    "subscription_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.subscriptiontype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Transaction",
                "verbose_name_plural": "Financial Transactions",
                "db_table": "financial_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
