# Generated by Django 4.2.7 on 2025-09-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0013_financialtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontype",
            name="max_tokens_free",
            field=models.IntegerField(
                default=0,
                help_text="Maximum free tokens allowed for this subscription (0 for unlimited)",
            ),
        ),
    ]
