# Generated by Django 4.2.7 on 2025-09-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0014_subscriptiontype_max_tokens_free"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userusage",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="userusage",
            name="period_end",
        ),
        migrations.RemoveField(
            model_name="userusage",
            name="period_start",
        ),
    ]
