# Generated by Django 4.2.7 on 2025-09-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_alter_userusage_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSubscriptionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Subscription Settings', max_length=100)),
                ('default_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_settings', to='subscriptions.subscriptiontype')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Default Subscription Settings',
                'verbose_name_plural': 'Default Subscription Settings',
                'db_table': 'default_subscription_settings',
            },
        ),
    ]