# Generated by Django 4.2.7 on 2025-09-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0016_defaultsubscriptionsettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DefaultSubscriptionSettings",
        ),
    ]
