# Generated by Django 4.2.7 on 2025-10-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0017_delete_defaultsubscriptionsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontype",
            name="max_openrouter_cost_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Maximum OpenRouter API cost in USD allowed for this subscription (0 for unlimited)",
                max_digits=10,
            ),
        ),
    ]
